In [6]:
# Import NumPy and give it the conventional short name np.
import numpy as np

# Import pandas and give it the conventional short name pd.
import pandas as pd

# Import Matplotlib's pyplot interface for plotting.
import matplotlib.pyplot as plt

# Import Seaborn for statistical graphics.
import seaborn as sns

# Import Plotly Express for interactive graphics.
import plotly.express as px

# Import SciPy's statistics module for inferential tests.
from scipy import stats

# Import Path to work with file paths cleanly.
from pathlib import Path

# Make pandas display more columns when we inspect a DataFrame.
pd.set_option("display.max_columns", 50)

# Set a clean Seaborn plotting theme.
sns.set_theme(style="whitegrid")

# Use the first color from the active plotting theme for single-series Seaborn plots.
DEFAULT_COLOR = sns.color_palette()[0]

print("Libraries imported successfully.")

Libraries imported successfully.


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
from pathlib import Path
import pandas as pd

# Define the dataset path.
DATA_PATH = Path("/content/Titanic-Dataset.csv")

# Check whether the dataset exists.
if not DATA_PATH.exists():
    try:
        from google.colab import files
        uploaded = files.upload()
        DATA_PATH = Path(next(iter(uploaded.keys())))
    except Exception as e:
        raise FileNotFoundError(
            "Titanic-Dataset.csv was not found. Please upload the file and run this cell again."
        ) from e

# Read the CSV file into a pandas DataFrame.
df_raw = pd.read_csv(DATA_PATH)

# Display the first five observations.
df_raw.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [11]:
# Basics Explore
print("Shape:",df_raw.shape )
print("\nMissing values:")
print(df_raw.isna().sum())
print("\nExact duplicate rows:", df_raw.duplicated().sum())
print("\nData types:")
print(df_raw.dtypes)

Shape: (891, 12)

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Exact duplicate rows: 0

Data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [14]:
# 1. NumPy for Scientific Computing
scores = np.array([65,72,80,91,88]) # Create a one-dimensional Numpy array.
# Display the array
print("Array:",scores)
# Display the Numpy objective type
print("Object type:", type(scores))
x.mean()


Array: [65 72 80 91 88]
Object type: <class 'numpy.ndarray'>


np.float64(20.0)

In [19]:
#2. Arrays and Dimensions: Create a two dimensional Array(Matrix)
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# View the matrix
print( matrix)
print("Shape:", matrix.shape)
print("Total elements:", matrix.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Total elements: 9


In [26]:
# Indexing and Slicing
x = np.array([10, 20, 30,40,50,60])
# First Value: Python inexing starts at 0.
print("First:", x[0])
print("Last:", x[-1]) # -1 means the final position
print("Slice from index 1 upto four", x[1:4])
print("First three values:", x[:3]) # First three values
print("x[::2]", x[::2])

First: 10
Last: 60
Slice from index 1 upto four [20 30 40]
First three values: [10 20 30]
x[::2] [10 30 50]


In [30]:
# Select the value in row 0, column 1.
print("matrix[0,1]=", matrix[0,1])
#Select a 2* 2 block from the upper left area
print("2*2 :\n", matrix[:2,2])
# Select the second column
print("Second column:", matrix[:,1])

matrix[0,1]= 2
2*2 :
 [3 6]
Second column: [2 5 8]


In [37]:
# Array Operations
a = np.array([1, 2, 3, 4, 5, 6])
# Add 10 to every element.
print("a+10=", a+10)
# Multiply every element by 2
print("a*2=", a*2)
# Squared every element
print(" a squared =", a**2)
# Take the sqaure root of every element.
print("sqrt(a)=",np.sqrt(a))

a+10= [11 12 13 14 15 16]
a*2= [ 2  4  6  8 10 12]
 a squared = [ 1  4  9 16 25 36]
sqrt(a)= [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [ ]:
# Vectorization

In [44]:
# Broadcastings
x = np.array([10, 20, 30])
x + 5
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix + np.array([10, 20, 30])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [47]:
# Mathematical & Statistical Functions
values = np.array([10,12,15,18,20,25,30])
# Calculate common summarizes
print("Count:", values.size)
print("Mean:", np.mean(values))
print("Median:", np.median(values))
print("Minimum:", np.min(values))
print("Maximum:", np.max(values))
print("Range:", np.max(values)-np.min(values))

print("Sample variance:", np.var(values,ddof =1)) # ddof(degress of freedom) = 1 gives the sample variance and sample standard deviation
print("sample SD:", np.std(values, ddof=1))
q1, median, q3= np.percentile(values, [25,50,75]) # median=q2
print("Q1:", q1)
print("Median:", median)
print("Q3:", q3)
print("IQR", q3-q1)

Count: 7
Mean: 18.571428571428573
Median: 18.0
Minimum: 10
Maximum: 30
Range: 20
Sample variance: 50.61904761904762
sample SD: 7.114706432386907
Q1: 13.5
Median: 18.0
Q3: 22.5
IQR 9.0


In [51]:
# Linear Algebra Basics
# Define two matrics
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
    ])


In [60]:
# Element-wise multiplication
print("Element-wise multiplication:\n", A*B)
print("Matrix multiplication A @ B:\n", A @B )
# Transpose of A and B
print("\nTranspose of A:\n", A.T)
print("\nTranspose of B:\n", B.T)
# Determinant of A
print("Determinant of A:", np.linalg.det(A))
# Inverse of A
print("Inverse of A:", np.linalg.inv(A))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication A @ B:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Transpose of B:
 [[5 7]
 [6 8]]
Determinant of A: -2.0000000000000004
Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]


In [65]:
# Solve system of linear equation
# 2x+ y = 5
# x-y = 1

coefficients = np.array([
    [2,1],
    [1,-1]
])
constants = np.array([5, 1])
solution = np.linalg.solve(coefficients, constants)
print("Solution:", solution)

Solution: [2. 1.]
